--
-- PostgreSQL database dump
--

\restrict 0ggpIlhcqKAyB6IVm0HpAX6dxHAuUYMGrjuAMLa0dVgXFI9NSVYuJyykP2W7QBu

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: writing_answers; Type: TABLE DATA; Schema: elp; Owner: admin
--

COPY elp.writing_answers (id, question_id, answer, review) FROM stdin;
202509231816071793	202509221959342781	I'm come from Son La - a province in Viet Nam. Son La is located in the north side of Viet Nam and it is the third largest province in my country.	<p>- Improve lexical resource</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ north side -&gt; northern region</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ it is famous for ... / it is well-known as ...</p>\n<p>- Grammar mistake</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ I come from / I'm from instead of "I'm come from..."</p>\n<p></p>\n
202509231211290479	202509231204350340	I work as a developer in a finacial company, where I take responsibity for creating a application for trading bond. I'm enjoy this job because coding is one of my hobbies.	<p>- Grammar errors:</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ finacial -&gt; financial</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ a application -&gt; an application</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ trading bond -&gt; trading bonds</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ I'm enjoy -&gt; I enjoy</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ take responsibity -&gt; take responsibility</p>\n<p>- Vocabulary suggestion:</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ work in a financial company -&gt; work in finalcial sector</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ responsibility for creatinf -&gt; responsible for developing</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ coding is one of my hobbies -&gt; my passionate about programming</p>\n<p></p>\n
202509231249086047	202509231204350340	I'm software developer in a financial company, where I'm responsible for developing an application for trading bonds. I enjoy this job because coding has always been one of my hobbies, and it allows me to keep learning and solving new problems	<p>Grammar mistake:</p>\n<p>- I'm software developer -&gt; I'm a software developer</p>\n<p></p>\n<p>Flow:</p>\n<p>- Declare job -&gt; feeling (enjoy) -&gt; reason to that feeling</p>\n
202509231306288689	202509231258440503	When I have free time I often watch movies or random videos on youtube. And if I have a plan to hang out with my friends, we usually playing in parks or eating in restaurants.	<p>Grammar mistake:</p>\n<p>- we usually playing -&gt; we usually play (abverb of frequency + V base)</p>\n<p></p>\n<p>Flow:</p>\n<p>- Listing activities -&gt; Giving feelings or reasons</p>\n
202509231314514885	202509231258440503	When I have free time, I often watching movies or random videos on Youtube. On weekends, if I have a plan to hang out with my friend, we usually play at the parks to exercise after a long week of work. And after that we can grap a bite at some local food stores. I enjoy doing these activities because it helps me relieve stress and stay connected with people I care about.	<p>Suggestion:</p>\n<p>- If I have a plan to hang out -&gt; If I plant to hang out&nbsp;</p>\n<p>- play at the parks -&gt; go to the park</p>\n<p>- grap a bite -&gt; grab a bite</p>\n
202509231417407010	202509231403191738	There is one time where I was relly pround of myself. That is when I was still a university student and I was taking this one math course and it very hard. For example, one question can take up 30 minutes and 2 to 3 paper to complete. And in the middle term examination, I only got 2 out of 10 score. That is when I really scare about fail this course. I remember I study really hard and the day before final  term examination, I stay woke all night to study and when the time comes, I complete every questions except for the final question cause it's very hard. And after many days of waiting, I got 9.5 out of 10 and I was really happy and pround about myself. That really boots my confident and make me believe that the hard work will pay of.	<p><strong>Grammar:</strong></p>\n<p>- Tense consistancy:</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ When talking about past, using past tense, not present tense</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ There is one time -&gt; There was one time</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ I stay woke all night -&gt; I stayed up all night&nbsp;</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ make me believe -&gt; made me believe&nbsp;&nbsp;&nbsp;&nbsp;</p>\n<p></p>\n<p>Articles:</p>\n<p>- Missing verb in "It very hard" -&gt; It was very hard</p>\n<p>- I really scare about fail -&gt; I really scared about falling</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ Verb should be past tense "scared"</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ about + V-ing -&gt; about falling</p>\n<p></p>\n<p>Verb forms:</p>\n<p>- That really boots my confident -&gt; That really boosted my confidence</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ Past verb "boosted"</p>\n<p>&nbsp;&nbsp;&nbsp;&nbsp;+ confident (adj), confidence (noun)</p>\n<p></p>\n<p>Vocabulary issues:</p>\n<p>- pround -&gt; proud</p>\n<p>- stay woke -&gt; stayed up</p>\n<p>- comple every questions -&gt; completed every question</p>\n<p></p>\n<p>Synomy:</p>\n<p>- really hard = extremely challenging</p>\n<p>- really happy = overjoys = trememdous sense of accomplishment</p>\n<p></p>\n<p>Idioms:</p>\n<p>- I was on the cloud nine (happy)</p>\n<p>- It was a turning point for me (impactful momment)</p>\n<p></p>\n<p>Linking words:</p>\n<p>- At first, However, Eventually, Finally, As a result</p>\n
202509261402135442	202509231403191738	There was one time where I was really proud of myself. That is when I was still a university student and I was taking this one math course and it extremely challenging. For example, one question can take up to 30 minutes and few papers to complete. And in the middle term examination, I only got 2 out of 10 score. At first, I was scared about failling this cource and that was a turning point for me. I remembered I studied really hard and in the day before the final exam, I stayed up all night to solve problems. Eventually, when the time came, I completed every questions except for the final question which is unsolvable to me at that moment. Finally, after many days of waiting, I got 9.5 out of 10 and I was on the cloud nine. That experience really boosted my confidence and it made me realize that the hard work always pays off. 	<p>few papers -&gt; a few papes</p>\n<p>+ few = not many (negative)</p>\n<p>+ a few = small but sufficient (positive)</p>\n<p></p>\n<p>middle term examination -&gt; "midterm exam" for short</p>\n<p></p>\n<p>spelling error:</p>\n<p>- scared about failling this cource -&gt; scared about <strong>failing </strong>this <strong>course</strong></p>\n<p></p>\n<p>complete every questions -&gt; complete every question</p>\n<p>- every + số ít</p>\n<p></p>\n<p>on the cloud nine -&gt; on cloud nine</p>\n<p></p>\n<p>unsolvable to me -&gt; imposible for me to solve (more natural)</p>\n<p></p>\n<p></p>\n<p></p>\n<p></p>\n
202510100210211811	202510100159365165	My country, Viet Nam, is famous for it's delicious food and stunning natural scenery. \n- For example, dishes like pho or banh mi are loved by both locals and tourists\n- Apart from that, places like Ha Long Bay and Sapa attract millions of visitors every year\n- And Vietnamese people is known for being warn and hospitable. Which make our country even more special	<p>Cấu trúc: Đồ ăn + Phong cảnh + Con người</p>\n<p></p>\n<p>Diễn đạt lại (paraphrase):</p>\n<p>- For example = such as, as an examle, to illustrate, for instance, in particular, namely</p>\n<p>- Apart from that = besides that, in addition to, aside from that, what more, futhermore, moreover</p>\n<p>- Foods: bún riêu, bún cá, bánh quấn, bún bò huế, bánh xèo, cà phê trứng</p>\n<p>- Places: Đà Nẵng, Hội An, Huế, Ninh Bình (Hạ Long Bay trên cạn)</p>\n<p>- Peoples: persistent (kiên cường), hard-working, welcoming (hiếu khách), generous (rộng lượng)</p>\n
202510100250029043	202510100159365165	My country, Vietnam, is well known for tasty cuisines and breathtaking natural landscapes.\n- To illustrate, dishes like Banh Xeo and Bun Rieu are enjoyed by people from near or far\n- In addition, places like Da Nang city or Hoi An night market receive millions of travelers annually\n- And our people is known for persistent and welcoming. Which makes Vietnam a country worth to visit.	<p>cruisine là danh từ không đếm được</p>\n<p>- cruisines -&gt; cruisine</p>\n<p></p>\n<p>people is -&gt; people are (số nhiều)</p>\n<p></p>\n<p>worth + V-ing</p>\n<p>- worth to visit -. worth visiting</p>\n<p>- Sau worth là danh (cái gì đó đáng giá để thử)</p>\n<p>- Gerund là dạng của verb nhưng có chức năng là noun</p>\n<p>- worth + visiting (noun)</p>\n<p></p>\n
\.


--
-- PostgreSQL database dump complete
--

\unrestrict 0ggpIlhcqKAyB6IVm0HpAX6dxHAuUYMGrjuAMLa0dVgXFI9NSVYuJyykP2W7QBu

